% solar_suitability_heatmap.m
% MATLAB script to create a heatmap based on dynamically provided data
% and save it as an SVG file.

% Load the data from the .mat file (which was saved from Python)
data = load('regions_data.mat');  % Make sure this file is generated by your Python script

% Extract latitude, longitude, and suitability scores
latitude = data.latitude;  % Example: [34.0522, 34.0400, 34.0600]
longitude = data.longitude;  % Example: [-118.2437, -118.2500, -118.2300]
suitability = data.suitability;  % Example: [0.8, 0.9, 0.85]

% Create a grid for the heatmap
lat_grid = linspace(min(latitude) - 0.05, max(latitude) + 0.05, 100);
lon_grid = linspace(min(longitude) - 0.05, max(longitude) + 0.05, 100);
[lat_mesh, lon_mesh] = meshgrid(lat_grid, lon_grid);

% Interpolate the suitability data onto the grid
suitability_grid = griddata(latitude, longitude, suitability, lat_mesh, lon_mesh, 'cubic');

% Plot the heatmap
figure;
imagesc(lon_grid, lat_grid, suitability_grid);
set(gca, 'YDir', 'normal');  % Correct y-axis direction
colorbar;
title('Solar Panel Installation Suitability Heatmap');
xlabel('Longitude');
ylabel('Latitude');

% Overlay original locations as points
hold on;
scatter(longitude, latitude, 100, 'red', 'filled');  % Mark the locations
hold off;

% Save the heatmap as an SVG file
saveas(gcf, './output/heatmap.svg');
